export const galleryContent = {
  en: {
    eyebrow: "Explore my work",
    title: ["Four areas.", "A bigger picture."],
    intro:
      "Education, professional experience, projects and community work — connected by a shared focus on renewable energy, data and people.",
    purpose: ["Different areas.", "A common purpose."],
    purposeText: "For a more informed and inclusive society.",
    explore: "Choose a room to explore",
    enter: "Enter",
    overview: "Overview",
    story: "Story",
    rooms: {
      experience: "Experience",
      projects: "Projects",
      volunteering: "Volunteering",
      education: "Education",
    },
    shortRooms: {
      experience: "Experience",
      projects: "Projects",
      volunteering: "Volunteer",
      education: "Education",
    },
    descriptions: {
      experience:
        "Two years exploring renewable power markets, policy and data at Veyt.",
      projects:
        "Data and analysis platforms that make energy information easier to follow, compare and understand.",
      volunteering:
        "Making useful information and a sense of belonging accessible to Arabic-speaking communities in Norway.",
      education:
        "An engineering foundation and a systems perspective on the energy transition.",
    },
    room: "Room",
    of: "of",
    next: "Continue to",
    present: "present",
    skill: "Skill",
    visited: "Visited",
    menu: "Open menu",
    closeMenu: "Close menu",
    skip: "Skip to content",
    digital: "Digital work",
    visuals: "Photography & film",
    contact: "Let’s connect",
    openProject: "Open project",
    projectDetails: "Explore project",
    focus: "Areas of focus",
    internship: "2-year internship",
    role: "Renewable power market analyst",
    scope: "Markets · Policy · Data",
    allRooms: "The whole gallery",
    backGallery: "Back to the gallery",
    more: "Beyond the four rooms",
    journey: "A connected journey",
    previousImage: "Previous image",
    nextImage: "Next image",
    enlarge: "View photograph",
    video: "Watch featured drone video",
    imageCount: "Image",
    galleryAlt:
      "Four connected sandstone exhibition rooms for experience, projects, volunteering and education, surrounded by trees and water.",
    roomAlt: {
      experience:
        "Sunlit Veyt exhibition room with a teal wall and sandstone arch.",
      projects:
        "Syrian Renewables exhibition room overlooking turbines and a coastal landscape.",
      volunteering:
        "Norway Now exhibition room with a sculpture representing community.",
      education:
        "Education exhibition room with NTNU and University of Oslo degree plaques.",
    },
    loadingError:
      "The illustration could not load. You can still explore every room below.",
    footer: "Energy · Data · Communication",
    based: "Oslo, Norway",
    external: "Opens in a new tab",
    email: "Email me",
    linkedin: "Connect on LinkedIn",
  },
  ar: {
    eyebrow: "استكشف أعمالي",
    title: ["أربعة مجالات.", "صورة أشمل."],
    intro:
      "الدراسة والخبرة المهنية والمشاريع والعمل المجتمعي — تجمعها رؤية مشتركة للطاقة المتجددة والبيانات والإنسان.",
    purpose: ["مجالات مختلفة.", "غاية مشتركة."],
    purposeText: "من أجل مجتمع أكثر معرفة وشمولاً.",
    explore: "اختر قاعة وابدأ الاستكشاف",
    enter: "ادخل",
    overview: "نظرة عامة",
    story: "القصة",
    rooms: {
      experience: "الخبرة العملية",
      projects: "المشاريع",
      volunteering: "العمل التطوعي",
      education: "الدراسة",
    },
    shortRooms: {
      experience: "خبرة",
      projects: "مشاريع",
      volunteering: "تطوع",
      education: "دراسة",
    },
    descriptions: {
      experience:
        "سنتان في تحليل أسواق الطاقة المتجددة والسياسات والبيانات لدى Veyt.",
      projects:
        "منصات بيانات وتحليل تجعل معلومات الطاقة أسهل في المتابعة والمقارنة والفهم.",
      volunteering:
        "معلومات مفيدة وروابط مجتمعية تدعم الناطقين بالعربية في النرويج.",
      education:
        "أساس هندسي ورؤية متكاملة لأنظمة الطاقة والتحول نحو مصادر متجددة.",
    },
    room: "القاعة",
    of: "من",
    next: "تابع إلى",
    present: "حتى الآن",
    skill: "مهارة",
    visited: "تمت زيارتها",
    menu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    skip: "انتقل إلى المحتوى",
    digital: "الأعمال الرقمية",
    visuals: "التصوير والفيديو",
    contact: "لنتواصل",
    openProject: "افتح المشروع",
    projectDetails: "استكشف المشروع",
    focus: "مجالات التركيز",
    internship: "تدريب لمدة سنتين",
    role: "محلل أسواق الطاقة المتجددة",
    scope: "الأسواق · السياسات · البيانات",
    allRooms: "المعرض كاملاً",
    backGallery: "العودة إلى المعرض",
    more: "ما وراء القاعات الأربع",
    journey: "مسيرة مترابطة",
    previousImage: "الصورة السابقة",
    nextImage: "الصورة التالية",
    enlarge: "عرض الصورة",
    video: "شاهد فيديو الدرون المختار",
    imageCount: "الصورة",
    galleryAlt:
      "أربع قاعات عرض من الحجر الرملي متصلة بممرات ذهبية للخبرة والمشاريع والتطوع والدراسة، تحيط بها الأشجار والمياه.",
    roomAlt: {
      experience: "قاعة Veyt بجدار أخضر داكن وقوس حجري تضيئها الشمس.",
      projects: "قاعة Syrian Renewables تطل على توربينات رياح ومشهد ساحلي.",
      volunteering: "قاعة Norway Now مع منحوتة تعبر عن الترابط المجتمعي.",
      education: "قاعة الدراسة مع لوحتي درجتي جامعة NTNU وجامعة أوسلو.",
    },
    loadingError:
      "تعذّر تحميل الصورة. يمكنك استكشاف جميع القاعات من الروابط أدناه.",
    footer: "الطاقة · البيانات · التواصل",
    based: "أوسلو، النرويج",
    external: "يفتح في علامة تبويب جديدة",
    email: "راسلني",
    linkedin: "تواصل عبر LinkedIn",
  },
  no: {
    eyebrow: "Utforsk arbeidet mitt",
    title: ["Fire områder.", "Et større bilde."],
    intro:
      "Utdanning, yrkeserfaring, prosjekter og samfunnsarbeid — knyttet sammen av fornybar energi, data og mennesker.",
    purpose: ["Ulike områder.", "Et felles formål."],
    purposeText: "For et mer informert og inkluderende samfunn.",
    explore: "Velg et rom og utforsk",
    enter: "Gå inn",
    overview: "Oversikt",
    story: "Historien",
    rooms: {
      experience: "Erfaring",
      projects: "Prosjekter",
      volunteering: "Frivillig arbeid",
      education: "Utdanning",
    },
    shortRooms: {
      experience: "Erfaring",
      projects: "Prosjekter",
      volunteering: "Frivillig",
      education: "Utdanning",
    },
    descriptions: {
      experience:
        "To år med analyse av fornybare kraftmarkeder, politikk og data hos Veyt.",
      projects:
        "Data- og analyseplattformer som gjør energiinformasjon enklere å følge, sammenligne og forstå.",
      volunteering:
        "Nyttig informasjon og fellesskap for arabisktalende mennesker i Norge.",
      education:
        "Et ingeniørfaglig grunnlag og et systemperspektiv på energiomstillingen.",
    },
    room: "Rom",
    of: "av",
    next: "Fortsett til",
    present: "nå",
    skill: "Ferdighet",
    visited: "Besøkt",
    menu: "Åpne meny",
    closeMenu: "Lukk meny",
    skip: "Hopp til innhold",
    digital: "Digitalt arbeid",
    visuals: "Foto og film",
    contact: "La oss ta kontakt",
    openProject: "Åpne prosjektet",
    projectDetails: "Utforsk prosjektet",
    focus: "Fokusområder",
    internship: "2-årig praksis",
    role: "Analytiker for fornybare kraftmarkeder",
    scope: "Markeder · Politikk · Data",
    allRooms: "Hele galleriet",
    backGallery: "Tilbake til galleriet",
    more: "Utover de fire rommene",
    journey: "En sammenhengende reise",
    previousImage: "Forrige bilde",
    nextImage: "Neste bilde",
    enlarge: "Se fotografiet",
    video: "Se utvalgt dronevideo",
    imageCount: "Bilde",
    galleryAlt:
      "Fire sammenkoblede utstillingsrom i sandstein for erfaring, prosjekter, frivillig arbeid og utdanning, omgitt av trær og vann.",
    roomAlt: {
      experience: "Solbelyst Veyt-rom med mørk grønn vegg og sandsteinbue.",
      projects: "Syrian Renewables-rom med vindturbiner og kystlandskap.",
      volunteering:
        "Norway Now-rom med en skulptur som symboliserer fellesskap.",
      education:
        "Utdanningsrom med gradstavler fra NTNU og Universitetet i Oslo.",
    },
    loadingError:
      "Illustrasjonen kunne ikke lastes. Du kan fortsatt utforske rommene nedenfor.",
    footer: "Energi · Data · Kommunikasjon",
    based: "Oslo, Norge",
    external: "Åpnes i en ny fane",
    email: "Send e-post",
    linkedin: "Kontakt på LinkedIn",
  },
  fr: {
    eyebrow: "Découvrez mon travail",
    title: ["Quatre domaines.", "Une vue d’ensemble."],
    intro:
      "Formation, expérience, projets et engagement associatif — reliés par les énergies renouvelables, les données et les personnes.",
    purpose: ["Différents domaines.", "Une même ambition."],
    purposeText: "Pour une société mieux informée et plus inclusive.",
    explore: "Choisissez une salle à explorer",
    enter: "Entrer",
    overview: "Vue d’ensemble",
    story: "Histoire",
    rooms: {
      experience: "Expérience",
      projects: "Projets",
      volunteering: "Bénévolat",
      education: "Formation",
    },
    shortRooms: {
      experience: "Expérience",
      projects: "Projets",
      volunteering: "Bénévolat",
      education: "Formation",
    },
    descriptions: {
      experience:
        "Deux ans d’analyse des marchés de l’électricité renouvelable, des politiques et des données chez Veyt.",
      projects:
        "Des plateformes de données et d’analyse pour suivre, comparer et comprendre l’information énergétique.",
      volunteering:
        "Une information utile et des liens communautaires pour les arabophones en Norvège.",
      education:
        "Une base en ingénierie et une vision systémique de la transition énergétique.",
    },
    room: "Salle",
    of: "sur",
    next: "Continuer vers",
    present: "aujourd’hui",
    skill: "Compétence",
    visited: "Visitée",
    menu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    skip: "Aller au contenu",
    digital: "Travail numérique",
    visuals: "Photographie et film",
    contact: "Échangeons",
    openProject: "Ouvrir le projet",
    projectDetails: "Explorer le projet",
    focus: "Domaines d’intérêt",
    internship: "Stage de 2 ans",
    role: "Analyste des marchés de l’électricité renouvelable",
    scope: "Marchés · Politiques · Données",
    allRooms: "Tout le parcours",
    backGallery: "Retour au parcours",
    more: "Au-delà des quatre salles",
    journey: "Un parcours connecté",
    previousImage: "Image précédente",
    nextImage: "Image suivante",
    enlarge: "Voir la photographie",
    video: "Voir la vidéo drone",
    imageCount: "Image",
    galleryAlt:
      "Quatre salles d’exposition en grès reliées, consacrées à l’expérience, aux projets, au bénévolat et à la formation, entourées d’arbres et d’eau.",
    roomAlt: {
      experience:
        "Salle Veyt ensoleillée avec un mur vert foncé et une arche en grès.",
      projects:
        "Salle Syrian Renewables avec des éoliennes et un paysage côtier.",
      volunteering:
        "Salle Norway Now avec une sculpture représentant la communauté.",
      education:
        "Salle de formation avec les diplômes de NTNU et de l’Université d’Oslo.",
    },
    loadingError:
      "L’illustration n’a pas pu être chargée. Les salles restent accessibles ci-dessous.",
    footer: "Énergie · Données · Communication",
    based: "Oslo, Norvège",
    external: "S’ouvre dans un nouvel onglet",
    email: "Envoyez-moi un e-mail",
    linkedin: "Échanger sur LinkedIn",
  },
};

export const roomPositions = {
  experience: { x: 47.6, y: 32.3 },
  projects: { x: 73, y: 58 },
  volunteering: { x: 56.8, y: 87 },
  education: { x: 36.5, y: 54 },
};
