export const houseContent = {
  en: {
    eyebrow: "The home of my work",
    title: ["Step inside", "my world."],
    intro: "Energy, ideas and people. A walk through the things that shape me.",
    scroll: "Scroll to enter",
    continue: "Keep scrolling to explore",
    look: "Drag sideways to look around",
    direct: "Browse sections",
    start: "Step inside",
    entrance: "At the front door",
    terrace: "There’s more to the story.",
    closing: "Photography, digital work and the people behind it all.",
    room: "Inside the house",
    read: "Explore this chapter",
    restart: "Back to the front door",
    directoryTitle: "Every room tells a story.",
    directoryIntro:
      "Go straight to a chapter, or return to the house for the full walk.",
    loading: "Opening the front door…",
    flat: "Explore the chapters below.",
    scene:
      "A three-dimensional house: scroll to walk through the front door and four rooms",
    chapters: "Jump to a room in the house",
    keyboard:
      "Use the room buttons to move through the house, or browse the sections for direct access. Normal page scrolling and browser zoom remain available.",
  },
  ar: {
    eyebrow: "بيت يجمع أعمالي",
    title: ["ادخل إلى", "عالمي."],
    intro: "الطاقة والأفكار والإنسان. جولة بين الأشياء التي صنعت مسيرتي.",
    scroll: "مرّر للدخول",
    continue: "تابع التمرير لتستكشف",
    look: "اسحب أفقيًا لتنظر حولك",
    direct: "تصفّح الأقسام",
    start: "ادخل إلى البيت",
    entrance: "عند باب البيت",
    terrace: "للقصة جوانب أخرى.",
    closing: "التصوير والعمل الرقمي والأشخاص وراء هذه المسيرة.",
    room: "داخل البيت",
    read: "استكشف هذا الفصل",
    restart: "العودة إلى باب البيت",
    directoryTitle: "في كل غرفة، حكاية.",
    directoryIntro:
      "انتقل مباشرة إلى أحد الأقسام، أو عُد إلى البيت لتكمل الجولة.",
    loading: "نفتح باب البيت…",
    flat: "استكشف الأقسام أدناه.",
    scene: "منزل ثلاثي الأبعاد: مرّر لتدخل من الباب وتتجول بين أربع غرف",
    chapters: "انتقل إلى غرفة داخل البيت",
    keyboard:
      "استخدم أزرار الغرف للتنقل داخل البيت، أو تصفّح الأقسام للوصول المباشر. يبقى تمرير الصفحة وتكبير المتصفح متاحين.",
  },
  no: {
    eyebrow: "Et hjem for arbeidet mitt",
    title: ["Kom inn i", "min verden."],
    intro:
      "Energi, ideer og mennesker. En vandring gjennom det som former meg.",
    scroll: "Rull for å gå inn",
    continue: "Fortsett å rulle og utforske",
    look: "Dra sidelengs for å se deg rundt",
    direct: "Se alle områder",
    start: "Kom inn",
    entrance: "Ved inngangsdøren",
    terrace: "Historien fortsetter.",
    closing: "Foto, digitalt arbeid og menneskene bak det hele.",
    room: "Inne i huset",
    read: "Utforsk dette kapittelet",
    restart: "Tilbake til inngangsdøren",
    directoryTitle: "Hvert rom har en historie.",
    directoryIntro:
      "Gå rett til et område, eller tilbake til huset for hele vandringen.",
    loading: "Åpner inngangsdøren…",
    flat: "Utforsk områdene nedenfor.",
    scene: "Et tredimensjonalt hus: rull gjennom inngangsdøren og fire rom",
    chapters: "Gå til et rom i huset",
    keyboard:
      "Bruk romknappene for å bevege deg gjennom huset, eller se alle områder for direkte tilgang. Vanlig siderulling og nettleserzoom er tilgjengelig.",
  },
  fr: {
    eyebrow: "Une maison pour mon travail",
    title: ["Entrez dans", "mon univers."],
    intro:
      "Énergie, idées et liens humains. Une promenade à travers ce qui me façonne.",
    scroll: "Défilez pour entrer",
    continue: "Continuez à défiler pour explorer",
    look: "Glissez horizontalement pour regarder autour de vous",
    direct: "Voir les rubriques",
    start: "Entrez",
    entrance: "À la porte d’entrée",
    terrace: "L’histoire continue.",
    closing:
      "Photographie, travail numérique et personnes derrière ce parcours.",
    room: "À l’intérieur",
    read: "Explorez ce chapitre",
    restart: "Retour à la porte d’entrée",
    directoryTitle: "Chaque pièce raconte une histoire.",
    directoryIntro:
      "Accédez directement à une rubrique, ou revenez à la maison pour la promenade complète.",
    loading: "La porte s’ouvre…",
    flat: "Explorez les rubriques ci-dessous.",
    scene:
      "Une maison en trois dimensions : défilez pour entrer et découvrir quatre pièces",
    chapters: "Accédez à une pièce de la maison",
    keyboard:
      "Utilisez les boutons des pièces pour parcourir la maison, ou les rubriques pour un accès direct. Le défilement et le zoom du navigateur restent disponibles.",
  },
};
