export const media = {
  gallery: [
    {
      id: "coastal-island",
      type: "image",
      src: "/media/photography/coastal-island.webp",
      width: 560,
      height: 386,
      alt: {
        en: "Aerial view of a green coastal island surrounded by clear blue water, with a Norwegian town in the background.",
        ar: "لقطة جوية لجزيرة ساحلية خضراء تحيط بها مياه زرقاء صافية، مع مدينة نرويجية في الخلفية.",
        no: "Luftfoto av en grønn kystøy omgitt av klart blått vann, med en norsk by i bakgrunnen.",
        fr: "Vue aérienne d’une île côtière verdoyante entourée d’une eau bleue claire, avec une ville norvégienne en arrière-plan.",
      },
      caption: {
        en: "Coastal aerial landscape — Norway",
        ar: "مشهد ساحلي جوي — النرويج",
        no: "Kystlandskap fra luften — Norge",
        fr: "Paysage côtier aérien — Norvège",
      },
    },
    {
      id: "autumn-lake",
      type: "image",
      src: "/media/photography/autumn-lake.webp",
      width: 280,
      height: 266,
      alt: {
        en: "Top-down drone view of a lake surrounded by vivid autumn forest, roads and nearby buildings.",
        ar: "لقطة درون عمودية لبحيرة تحيط بها غابة خريفية زاهية وطرق ومبانٍ قريبة.",
        no: "Dronebilde ovenfra av en innsjø omgitt av sterke høstfarger, veier og bygninger.",
        fr: "Vue verticale par drone d’un lac entouré d’une forêt automnale colorée, de routes et de bâtiments.",
      },
      caption: {
        en: "Autumn colours from above",
        ar: "ألوان الخريف من الأعلى",
        no: "Høstfarger sett ovenfra",
        fr: "Couleurs d’automne vues du ciel",
      },
    },
    {
      id: "emerald-beach",
      type: "image",
      src: "/media/photography/emerald-beach.webp",
      width: 500,
      height: 198,
      wide: true,
      alt: {
        en: "Aerial panorama of an emerald bay, white sandy beaches, rocky coastline and nearby homes.",
        ar: "بانوراما جوية لخليج زمردي وشواطئ رملية بيضاء وساحل صخري ومنازل قريبة.",
        no: "Luftpanorama av en smaragdgrønn bukt, hvite sandstrender, steinete kyst og nærliggende boliger.",
        fr: "Panorama aérien d’une baie émeraude, de plages de sable blanc, d’une côte rocheuse et d’habitations voisines.",
      },
      caption: {
        en: "Emerald coast and light reflections",
        ar: "ساحل زمردي وانعكاسات ضوئية",
        no: "Smaragdkyst og lysrefleksjoner",
        fr: "Côte émeraude et reflets lumineux",
      },
    },
    {
      id: "drone-sunset",
      type: "image",
      src: "/media/photography/drone-sunset.webp",
      width: 760,
      height: 507,
      alt: {
        en: "Silhouette of a camera drone against an intense red and orange sunset.",
        ar: "صورة ظلية لدرون تصوير أمام غروب أحمر وبرتقالي متوهج.",
        no: "Silhuett av en kameradrone mot en intens rød og oransje solnedgang.",
        fr: "Silhouette d’un drone-caméra devant un coucher de soleil rouge et orange intense.",
      },
      caption: {
        en: "Drone silhouette at sunset",
        ar: "درون عند الغروب",
        no: "Drone-silhuett ved solnedgang",
        fr: "Silhouette de drone au coucher du soleil",
      },
    },
    {
      id: "forest-stream",
      type: "image",
      src: "/media/photography/forest-stream.webp",
      width: 160,
      height: 307,
      portrait: true,
      alt: {
        en: "Tall conifer forest viewed from below, with a narrow icy stream crossing the forest floor.",
        ar: "غابة صنوبرية كثيفة تُرى من الأسفل، يعبر أرضها جدول جليدي ضيق.",
        no: "Høy barskog sett nedenfra, med en smal islagt bekk gjennom skogbunnen.",
        fr: "Haute forêt de conifères vue d’en bas, traversée par un étroit ruisseau glacé.",
      },
      caption: {
        en: "Forest depth and winter stream",
        ar: "عمق الغابة وجدول شتوي",
        no: "Skogsdybde og vinterbekk",
        fr: "Profondeur de forêt et ruisseau hivernal",
      },
    },
    {
      id: "night-monument",
      type: "image",
      src: "/media/photography/night-monument.webp",
      width: 760,
      height: 507,
      alt: {
        en: "Night photograph of a monument beside the water beneath a star-filled sky.",
        ar: "صورة ليلية لنصب تذكاري بجانب الماء تحت سماء مليئة بالنجوم.",
        no: "Nattfoto av et monument ved vannet under en stjerneklar himmel.",
        fr: "Photographie nocturne d’un monument au bord de l’eau sous un ciel étoilé.",
      },
      caption: {
        en: "Night sky and monument",
        ar: "سماء ليلية ونصب تذكاري",
        no: "Nattehimmel og monument",
        fr: "Ciel nocturne et monument",
      },
    },
    {
      id: "youtube-showreel",
      type: "youtube",
      youtubeId: "2s6SVA58CCE",
      poster: "/media/photography/drone-sunset.webp",
      width: 760,
      height: 428,
      wide: true,
      alt: {
        en: "Video preview featuring drone filming and visual storytelling work.",
        ar: "معاينة فيديو تعرض أعمال تصوير الدرون والسرد البصري.",
        no: "Videoforhåndsvisning med droneopptak og visuell historiefortelling.",
        fr: "Aperçu vidéo présentant des prises de vue par drone et un travail de narration visuelle.",
      },
      caption: {
        en: "Featured drone video",
        ar: "فيديو درون مختار",
        no: "Utvalgt dronevideo",
        fr: "Vidéo drone sélectionnée",
      },
    },
  ],
};
